### ISSUE TITLE
HTML-Struktur verletzt

### ISSUE THREAD

**Issue by L3P3** [Hoffalex0/Hoffsite#14]
In der Datei `projekte.html` wurde die [semantisch](https://www.alamy.de/yannis-tsarouchis-1910-1989-seemann-am-tisch-sitzend-rosa-hintergrund-1980-ol-auf-leinwand-an-bord-gelegt-100-73-cm-am-goulandris-image368905250.html) erforderliche Struktur verletzt:

1. Es befinden sich `p`-Elemente in anderen `p`-Elementen. Ein `p`-Element (p wie paragraph) ist ein Absatz, ein Textblock, also ein Block-Element (`display: block`). In einen Absatz dürfen nur Elemente, die sich in den Textfluss einordnen, z. B. `a`, `span`, `b`, `u`, `i` oder `img`. Statt `p` meintest du zur Schriftfarbenänderung vermutlich Jens `span`.

2. Es befinden sich Textfluss-Elemente (`display: inline`) in einem nicht-Text-Element bzw neben `p`-Elementen, ohne selbst in einem Blockelement zu sein. Der Link hinten in der Aufklappbox muss in ein `p`-Element rein.

**Comment by Hoffalex0** [comment]
Durch Update längst behoben.
