### ISSUE TITLE
Zugriffsbeschränkungen zur Qualitätssicherung

### ISSUE THREAD

**Issue by L3P3** [Hoffalex0/Hoffsite#15]
Momentan gibt es andere Nutzer, welche blöde HTML-Fehler #14 produzieren und von vielen Regeln offensichtlich keine Ahnung haben und nur danach gehen, was ihr armer Browser aus dem Grütz zusammenrät.

Im Namen des Browserschutzes (erweiterter Tierschutz) sollte dies unterbunden werden, etwa indem andere Nutzer für Änderungen Pull-Requests erstellen müssen und auf dem Hauptbranch selbst nichts machen können. Stichwort Sicherheit.

**Comment by L3P3** [comment]
Wurde das Problem behoben und die Push-Berechtigung für andere auf den Hauptbranch entzogen?

**Comment by Hoffalex0** [comment]
Das Problem wurde behoben.
