### ISSUE TITLE
SLBKSB ist nicht unwichtig

### ISSUE THREAD

**Issue by L3P3** [Hoffalex0/Hoffsite#16]
Also ist seine Seite auch nicht unwichtig.

Aber inaktiv, da kommt gemeinerweise seit langem nichts neues.

Also statt "unwichtige Seite" sollte da stehen "inaktive Seite". FINDE ICH!

**Comment by Hoffalex0** [comment]
SLBKSB wurde aus unterschiedlichen Gründen nicht mehr verlinkt.
