### ISSUE TITLE
Empfehlungsseite: Einführung zugeklappt

### ISSUE THREAD

**Issue by L3P3** [Hoffalex0/Hoffsite#18]
"Video-, Musik-, Text- und Rezeptempfehlungen" ist der Seitentitel, darunter kommt ein kurzer Satz, um in diese Seite einzuführen.
Warum ist die Einführung, welche immer ohne Interaktion sichtbar sein sollte, versteckt?!
UNLOGISCH

**Comment by Hoffalex0** [comment]
In der neuen Version wurde dieser Fehler durch eine neue Struktur behoben.
