### ISSUE TITLE
Links unten

### ISSUE THREAD

**Issue by L3P3** [Hoffalex0/Hoffsite#3]
1. Es fehlt vor `target=` ein Leerzeichen.
2. L3P3.de sollte mit HTTPS verlinkt werden.
3. Die URL für slbksb ist: `http://slbksb.de`
4. GitHub mit großem H.
5. `<br>` gehört zur endenden Zeile und nicht zur nächsten. Statt `<br><br>` sollten unbedingt `<p>` verwendet werden. Das eine `<br />` ist uneinheitlich.
6. YouTube-"Channel"? Uneinheitlich, "-Channel" sollte weg oder "GitHub-Konto" und "Giphy-Konto" usw.

**Comment by Hoffalex0** [comment]
fixed
