### ISSUE TITLE
Ergänzung

### ISSUE THREAD

**Issue by L3P3** [Hoffalex0/Hoffsite#4]
Schwächen: +Grammatik +HTML (beides _noch_)

**Comment by Hoffalex0** [comment]
Unverständliches Problem

**Comment by L3P3** [comment]
Auf Ihrer Selbstbeschreibung fehlen die beiden Schwächen. :P

**Comment by L3P3** [comment]
Ja, die fehlen ja auch, weil ich sie nicht habe. :PPP
