### ISSUE TITLE
Freundes-Skala sollte erklärt werden

### ISSUE THREAD

**Issue by L3P3** [Hoffalex0/Hoffsite#5]
Was heißt es, wenn man gelb ist?

- Bist du dir weniger sicher, ob es wirklich ein Freund ist?
- Zweifelst du an der Beständigkeit?
- Magst du jene Person weniger?
- Ist jene Person weniger nett zu dir?
- Kennst du jene Person weniger/kürzer?
- Heißt es garnichts und der Gradient ist nur Dekoration?

-> Darüber kurz hinschreiben.

**Comment by Hoffalex0** [comment]
Die Farbe grün symbolisiert eine gute Freundschaft. Je weiter gelb eine Person ist, desto eher bin ich mir unsicher, dass diese Freundschaft lange hält.

**Comment by Hoffalex0** [comment]
Fixed

**Comment by L3P3** [comment]
In der Commit-Bezeichnung solltest du #5 am Anfang stellen, um diesen Issue zu referenzieren.
