### ISSUE TITLE
Zensur

### ISSUE THREAD

**Issue by L3P3** [Hoffalex0/Hoffsite#7]
Unliebsame Artikel werden rückwirkend versteckt, doch das Internet vergisst nie!

**Comment by Hoffalex0** [comment]
Der Website-Besitzer schränkt den Zugriff auf manche Inhalte ein, da sie nicht mehr aktuell sind. Natürlich können diese Inhalte noch im GitHub-Verlauf gefunden werden.

**Comment by Hoffalex0** [comment]
Die Absicht war nicht die Löschung der Artikel.
