### ISSUE TITLE
Unnötige Platzhalter

### ISSUE THREAD

**Issue by L3P3** [Hoffalex0/Hoffsite#8]
Warum gibt es bei der Projektseite Trollboxen, in denen nach Aufklappen nichts drin ist?
Und so lustig so Aufklappboxen auch sind — hier ergeben die garkeinen Sinn. Warum soll man einmal klicken, nur um einen Link zu sehen? Einfach gleich den Link zeigen. Aufklappboxen nur bei unnötigen Details, um besseren Überblick zu ermöglichen. In einer Liste, wo man jeden Eintrag erst aufklappen muss [um überhaupt zu sehen, worum es geht, man muss also eh alles aufklappen!], unsinnig.

**Comment by Hoffalex0** [comment]
Antwort auf die Frage: Es sind noch kurze Projektzusammenfassungen mit Bild geplant. Diese brauchen viel Platz.

**Comment by L3P3** [comment]
Beantwortet nicht die Frage nach leeren Einträgen. Ein Produkt sollte immer JETZT gut verwendbar sein. Der unkundige Seitenbesucher ist nur vom Ist-Zustand genervt und den interessiert nicht, was du damit vorhast. Deine Website ist doch nicht dein Notizzettel oder deine private Zutun-Liste. :P
